title: Sucre
description: >- 
  Fedeindustria

baseurl: "https://fedeindustria.com/"

url: "https://fedeindustria.com/sucre" 

markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
